### PR TITLE
Fix logic of get_programs function 

### LINKED ISSUE #47: Fix logic of get_programs function
There is an error in the logic builds the situation for the simulation

### PR DESCRIPTION
**Pull request by ThapeloMasasa**
Fixes #47
adds the axes argument to the situation in an attempt to make the heatmap calculation faster

### CODE REVIEW

**Comment by ThapeloMasasa** [comment]
The issue that I am coming across is that the values that I get upon adding the axes are really low , while when I comment them out they are reasonable and with the expected range as can be seen by the picture below

With axes:
Screenshot 2024-04-02 at 8 57 24 AM
 Without Axes:
Screenshot 2024-04-02 at 5 39 38 PM

Also the generation of the heatmap is still long

**Comment by MaxGhenis** [comment]
Can you look at the values themselves? A notebook may help

**Comment by ThapeloMasasa** [comment]
> Can you look at the values themselves? A notebook may help

@MaxGhenis  the picture below is the notebook output of the same situation:
Screenshot 2024-04-03 at 3 53 09 PM

**Comment by MaxGhenis** [comment]
With axes I mean

**Comment by ThapeloMasasa** [comment]
> With axes I mean

@MaxGhenis it gives this output below: 
Screenshot 2024-04-03 at 5 28 35 PM

**Comment by MaxGhenis** [comment]
OK there's the problem. Please share your full notebook (e.g. as a Google Colab link).

**Comment by ThapeloMasasa** [comment]
> OK there's the problem. Please share your full notebook (e.g. as a Google Colab link).
@MaxGhenis  here it is:
https://colab.research.google.com/drive/1C69WT5rvo2M1M3BGiF13nZtpHbicIxA4?usp=drive-slack#scrollTo=0eHD_zofKYx1

**Comment by PavelMakarchuk** [comment]
> > With axes I mean
> 
> @MaxGhenis it gives this output below: Screenshot 2024-04-03 at 5 28 35 PM

@nikhilwoodruff or @anth-volk any idea why this would return nan's?

**Comment by ThapeloMasasa** [comment]
After figuring out the use of the axes, the heatmap generation has improved:

https://github.com/PolicyEngine/us-marriage-incentive/assets/73863365/d29a2e1e-3fc7-403a-973d-b6cf30c76bca

**Pull request merged**
