### PR TITLE
Change the heatmap from absolute values to percentage

### LINKED ISSUE #70: Change the heatmap from absolute values to percentage

### PR DESCRIPTION
**Pull request by ThapeloMasasa**
Fixes #70

Adds percentage values to the hover tool tip
Screenshot 2024-05-15 at 12 41 46 AM

### CODE REVIEW

**Comment by PavelMakarchuk** [comment]
We should try to have more gradual shading

**Comment by ThapeloMasasa** [comment]
`
Screenshot 2024-05-22 at 7 07 33 PM

**Comment by ThapeloMasasa** [comment]
https://github.com/PolicyEngine/us-marriage-incentive/assets/73863365/1fbb5f22-4f95-4ce5-a83f-a18ef59eb9af

**Comment by ThapeloMasasa** [comment]
https://github.com/PolicyEngine/us-marriage-incentive/assets/73863365/bbdc0aa4-9420-47b4-bbff-a7b9edeec3df

**Pull request merged**
