### PR TITLE
Include dependents into household composition

### LINKED ISSUE #4: Include dependents into household composition
Add kid to the partner with the higher income?

Once the kid is added we could generate a heatmap output showing whether the addition of a kid is changing the penalty / bonus situation.

### PR DESCRIPTION
**Pull request by ThapeloMasasa**
Fixes #4

### CODE REVIEW

**Comment by ThapeloMasasa** [comment]
@MaxGhenis  Is there a way to decrease computation time for the heat map values because it is taking a while to get a combination of head of household and spouse incomes.

**Review by MaxGhenis — COMMENTED** [review]
try the `axes` argument to Simulation. you can see the Reproduce in Python code with earnings variation for a household scenario in the app for an example. it'll make it much faster

**Comment by ThapeloMasasa** [comment]
> try the `axes` argument to Simulation. you can see the Reproduce in Python code with earnings variation for a household scenario in the app for an example. it'll make it much faster

@MaxGhenis I do not see the axes in the  reproduced python code on this link-->  https://policyengine.org/us/household?focus=householdOutput.pythonReproducibility&household=41487

**Comment by MaxGhenis** [comment]
Toggle `Include earning variation` at the top

**Comment by PavelMakarchuk** [comment]
Duplicate

**Pull request closed without merging**
