### PR TITLE
Swap not married and married & Add delta percentage

### LINKED ISSUE #43: Format Table: Swap Not Married and Married Columns & Add Delta in Percentage
Screenshot 2024-03-17 at 8 04 18 PM

### PR DESCRIPTION
**Pull request by emieelvire**
Fix #43

### CODE REVIEW

**Comment by PavelMakarchuk** [comment]
Could you add the screenshot once done?

**Comment by emieelvire** [comment]
Screenshot 2024-03-28 at 9 35 56 AM

**Comment by PavelMakarchuk** [comment]
> Screenshot 2024-03-28 at 9 35 56 AM

In this case, why would the delta % in the table be different from the % in the title, if the actual delta is the same?

**Comment by emieelvire** [comment]
Screenshot 2024-03-31 at 8 44 39 PM
fixed it! I was using the incorrect denominator.

**Pull request merged**
